from hardware.drivers.base_driver import DeviceDriver
from hardware.quartus.compiler import QuartusCompiler
from hardware.quartus.timing import TimingAnalyzer
from hardware.quartus.simulator import QuartusSimulator
from hardware.quartus.command import QuartusCommandError
from pathlib import Path
import pandas as pd
import logging

logger = logging.getLogger('ASIC Driver')

class ASICDriver(DeviceDriver):
    def __init__(self, project_path: Path, simulation_path: Path, name: str, compiler: QuartusCompiler, timing_analyzer: TimingAnalyzer, simulator: QuartusSimulator):
        super().__init__(project_path, simulation_path, name, compiler)
        self.timing_analyzer = timing_analyzer
        self.simulator = simulator
        
        self.last_params = {}
        self.fmax = None

    def prepare_hardware(self, params: dict) -> None:
        self.current_params = params
        structural_params = {k: v for k, v in params.items() if k != "input_file"}
        try:
            self._update_verilog_parameters(params)
        except FileNotFoundError as e:
            logger.error(f"Could not update parameters: {e}")
            raise

        if structural_params != self.last_params:
            logger.info(f"Structural parameters changed ({structural_params}). Re-compiling ASIC...")
            try:
                self.build()
                self.last_params = structural_params.copy()
            except QuartusCommandError:
                logger.error(f"Failed to compile {self.name}")
                raise
        else:
            logger.info("Structural parameters unchanged. Skipping Quartus build.")

        self._force_simulation_recompile()

    def _force_simulation_recompile(self):
        try:
            self.simulator.compile(self.project_path, self.simulation_path)
        except Exception as e:
            logger.error(f"Failed to update simulation files: {e}")

    def _update_verilog_parameters(self, params: dict) -> None:
        target_file = self.project_path / "hdl" / "PARAMETERS.vh"
        if not target_file.exists():
            target_file = self.project_path / "PARAMETERS.vh"
        
        if not target_file.exists():
            target_file = self.project_path / "hdl" / "PARAMETERS.vh"
            target_file.parent.mkdir(parents=True, exist_ok=True)

        logger.info(f"Writing N, M and FILE to {target_file}")
        
        param_mapping = {
            "sequence_1_size": "N",
            "sequence_2_size": "M",
            "input_file": "FILE"  
        }

        with open(target_file, "w") as f:
            f.write("// Auto-generated by ASICDriver.\n")
            
            for python_key, verilog_key in param_mapping.items():
                if python_key in params:
                    val = params[python_key]
                    
                    if isinstance(val, str):
                        f.write(f'parameter {verilog_key} = "{val}";\n')
                    else:
                        f.write(f'parameter {verilog_key} = {val};\n')

    def build(self) -> None:
        logger.info(f"Re-compiling ASIC project at {self.project_path}...")
        self.compiler.synthetize(project_path=self.device_path)
        self.compiler.fit(project_path=self.device_path)
        self.compiler.timing(project_path=self.device_path)
        
        self.fmax = self.timing_analyzer.get_fmax(self.device_path)
        if self.fmax:
            logger.info(f"New fmax for {self.name}: {self.fmax} MHz")

    def run_simulation(self, output_dir: Path) -> pd.DataFrame:
        sim_args = {
            "ID": output_dir.name,
            "DIR": output_dir.as_posix()
        }

        sim_work_dir = self.simulation_path / "simulation_files"
        script_path = sim_work_dir / "scripts" / "run.tcl"
        compiled_work_dir = sim_work_dir / "compiled_work"
        sim_work_dir.mkdir(parents=True, exist_ok=True)
        compiled_work_dir.mkdir(parents=True, exist_ok=True)
        script_path.parent.mkdir(parents=True, exist_ok=True)
        if not script_path.exists():
            logger.info(f"Generating run script at {script_path}")
            with open(script_path, "w") as f:
                f.write("onerror { quit -code 1 -f }\n") 
                f.write("onbreak { quit -code 1 -f }\n")
                f.write("run -all\n")
                f.write("quit -f")
        try:
            self.simulator.compile(project_path=self.project_path, simulation_path=self.simulation_path)
        except Exception as e:
            logger.error(f"Failed to compile simulation: {e}")
            return pd.DataFrame()    
        try:
            self.simulator.simulate(
                work_dir=sim_work_dir,
                tb_name="work.tb_asic",
                script_path=script_path,
                generics=sim_args,
                compiled_lib_path=compiled_work_dir
            )
        except Exception as e:
            logger.error(f"Simulation execution failed: {e}")
            return pd.DataFrame()
        
        results_file = output_dir / "output.csv" 
        return self._parse_results(results_file)
    

    def _parse_results(self, results_path: Path) -> pd.DataFrame:
        if not results_path.exists():
            logger.error(f"Simulation output not found at {results_path}")
            return pd.DataFrame()
        
        try:
            df = pd.read_csv(results_path, decimal=',', sep=';')
            if df.empty: return df

            df["device"] = self.name
            for param_name, param_value in self.current_params.items():
                df[param_name] = param_value

            if self.fmax:
                df["fmax_mhz"] = self.fmax
                if "cycles" in df.columns:
                    df["exec_time_s"] = df["cycles"] / (self.fmax * 1_000_000)
                    df["exec_time_ns"] = df["cycles"] / (self.fmax)
            else:
                df["fmax_mhz"] = float("nan")
            
            # Add extra information for better recovery
            df.to_csv(results_path, index=False, sep=';', decimal=',')
            
            return df
        except Exception as e:
            logger.error(f"Error parsing simulation results: {e}")
            return pd.DataFrame()